# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1144, 1019)
        MainWindow.setMinimumSize(QtCore.QSize(800, 935))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_file_data = QtWidgets.QFrame(self.centralwidget)
        self.frame_file_data.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_file_data.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_file_data.setObjectName("frame_file_data")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_file_data)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget_main = QtWidgets.QTabWidget(self.frame_file_data)
        self.tabWidget_main.setObjectName("tabWidget_main")
        self.tabWidget_guide = QtWidgets.QWidget()
        self.tabWidget_guide.setObjectName("tabWidget_guide")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tabWidget_guide)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_guide = QtWidgets.QVBoxLayout()
        self.verticalLayout_guide.setObjectName("verticalLayout_guide")
        self.label_window_parameters = QtWidgets.QLabel(self.tabWidget_guide)
        self.label_window_parameters.setMinimumSize(QtCore.QSize(0, 62))
        self.label_window_parameters.setMaximumSize(QtCore.QSize(16777215, 62))
        self.label_window_parameters.setObjectName("label_window_parameters")
        self.verticalLayout_guide.addWidget(self.label_window_parameters)
        self.frame_window = QtWidgets.QFrame(self.tabWidget_guide)
        self.frame_window.setMinimumSize(QtCore.QSize(370, 0))
        self.frame_window.setMaximumSize(QtCore.QSize(370, 16777215))
        self.frame_window.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_window.setObjectName("frame_window")
        self.formLayout_10 = QtWidgets.QFormLayout(self.frame_window)
        self.formLayout_10.setObjectName("formLayout_10")
        self.label_length = QtWidgets.QLabel(self.frame_window)
        self.label_length.setAccessibleDescription("")
        self.label_length.setOpenExternalLinks(False)
        self.label_length.setObjectName("label_length")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_length)
        self.doubleSpinBox_length_z = QtWidgets.QDoubleSpinBox(self.frame_window)
        self.doubleSpinBox_length_z.setMinimumSize(QtCore.QSize(0, 0))
        self.doubleSpinBox_length_z.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.doubleSpinBox_length_z.setDecimals(3)
        self.doubleSpinBox_length_z.setMinimum(0.001)
        self.doubleSpinBox_length_z.setMaximum(100000.0)
        self.doubleSpinBox_length_z.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.doubleSpinBox_length_z.setProperty("value", 10000.0)
        self.doubleSpinBox_length_z.setObjectName("doubleSpinBox_length_z")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_length_z)
        self.label_dist_z = QtWidgets.QLabel(self.frame_window)
        self.label_dist_z.setObjectName("label_dist_z")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_dist_z)
        self.doubleSpinBox_dist_z = QtWidgets.QDoubleSpinBox(self.frame_window)
        self.doubleSpinBox_dist_z.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.doubleSpinBox_dist_z.setDecimals(3)
        self.doubleSpinBox_dist_z.setMinimum(0.001)
        self.doubleSpinBox_dist_z.setMaximum(100000.0)
        self.doubleSpinBox_dist_z.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.doubleSpinBox_dist_z.setProperty("value", 1.0)
        self.doubleSpinBox_dist_z.setObjectName("doubleSpinBox_dist_z")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_dist_z)
        self.label_nbr_z_disp = QtWidgets.QLabel(self.frame_window)
        self.label_nbr_z_disp.setObjectName("label_nbr_z_disp")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_nbr_z_disp)
        self.spinBox_nbr_z_disp = QtWidgets.QSpinBox(self.frame_window)
        self.spinBox_nbr_z_disp.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.spinBox_nbr_z_disp.setMinimum(1)
        self.spinBox_nbr_z_disp.setMaximum(10000)
        self.spinBox_nbr_z_disp.setProperty("value", 200)
        self.spinBox_nbr_z_disp.setDisplayIntegerBase(10)
        self.spinBox_nbr_z_disp.setObjectName("spinBox_nbr_z_disp")
        self.formLayout_10.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox_nbr_z_disp)
        self.label_length_x = QtWidgets.QLabel(self.frame_window)
        self.label_length_x.setObjectName("label_length_x")
        self.formLayout_10.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_length_x)
        self.doubleSpinBox_length_x = QtWidgets.QDoubleSpinBox(self.frame_window)
        self.doubleSpinBox_length_x.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.doubleSpinBox_length_x.setDecimals(3)
        self.doubleSpinBox_length_x.setMinimum(0.001)
        self.doubleSpinBox_length_x.setMaximum(10000.0)
        self.doubleSpinBox_length_x.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.doubleSpinBox_length_x.setProperty("value", 1000.0)
        self.doubleSpinBox_length_x.setObjectName("doubleSpinBox_length_x")
        self.formLayout_10.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_length_x)
        self.label_dist_x = QtWidgets.QLabel(self.frame_window)
        self.label_dist_x.setObjectName("label_dist_x")
        self.formLayout_10.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_dist_x)
        self.doubleSpinBox_dist_x = QtWidgets.QDoubleSpinBox(self.frame_window)
        self.doubleSpinBox_dist_x.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.doubleSpinBox_dist_x.setDecimals(3)
        self.doubleSpinBox_dist_x.setMinimum(0.001)
        self.doubleSpinBox_dist_x.setMaximum(100.0)
        self.doubleSpinBox_dist_x.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.doubleSpinBox_dist_x.setProperty("value", 0.2)
        self.doubleSpinBox_dist_x.setObjectName("doubleSpinBox_dist_x")
        self.formLayout_10.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_dist_x)
        self.verticalLayout_guide.addWidget(self.frame_window)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_guide.addItem(spacerItem)
        self.label_guides_information = QtWidgets.QLabel(self.tabWidget_guide)
        self.label_guides_information.setMinimumSize(QtCore.QSize(0, 62))
        self.label_guides_information.setMaximumSize(QtCore.QSize(16777215, 62))
        self.label_guides_information.setObjectName("label_guides_information")
        self.verticalLayout_guide.addWidget(self.label_guides_information)
        self.frame_guides = QtWidgets.QFrame(self.tabWidget_guide)
        self.frame_guides.setMinimumSize(QtCore.QSize(370, 0))
        self.frame_guides.setMaximumSize(QtCore.QSize(370, 16777215))
        self.frame_guides.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_guides.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_guides.setObjectName("frame_guides")
        self.formLayout_6 = QtWidgets.QFormLayout(self.frame_guides)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_width = QtWidgets.QLabel(self.frame_guides)
        self.label_width.setObjectName("label_width")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_width)
        self.doubleSpinBox_width = QtWidgets.QDoubleSpinBox(self.frame_guides)
        self.doubleSpinBox_width.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.doubleSpinBox_width.setDecimals(3)
        self.doubleSpinBox_width.setMinimum(0.0)
        self.doubleSpinBox_width.setMaximum(10000.0)
        self.doubleSpinBox_width.setSingleStep(1.0)
        self.doubleSpinBox_width.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.doubleSpinBox_width.setProperty("value", 8.0)
        self.doubleSpinBox_width.setObjectName("doubleSpinBox_width")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_width)
        self.label_offset_guide = QtWidgets.QLabel(self.frame_guides)
        self.label_offset_guide.setObjectName("label_offset_guide")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_offset_guide)
        self.doubleSpinBox_offset_guide = QtWidgets.QDoubleSpinBox(self.frame_guides)
        self.doubleSpinBox_offset_guide.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.doubleSpinBox_offset_guide.setDecimals(3)
        self.doubleSpinBox_offset_guide.setMinimum(-5000.0)
        self.doubleSpinBox_offset_guide.setMaximum(5000.0)
        self.doubleSpinBox_offset_guide.setProperty("value", 0.0)
        self.doubleSpinBox_offset_guide.setObjectName("doubleSpinBox_offset_guide")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_offset_guide)
        self.doubleSpinBox_n = QtWidgets.QDoubleSpinBox(self.frame_guides)
        self.doubleSpinBox_n.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.doubleSpinBox_n.setDecimals(6)
        self.doubleSpinBox_n.setMinimum(1.0)
        self.doubleSpinBox_n.setMaximum(1000.0)
        self.doubleSpinBox_n.setSingleStep(0.1)
        self.doubleSpinBox_n.setProperty("value", 2.14)
        self.doubleSpinBox_n.setObjectName("doubleSpinBox_n")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_n)
        self.label_n = QtWidgets.QLabel(self.frame_guides)
        self.label_n.setObjectName("label_n")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_n)
        self.label_dn = QtWidgets.QLabel(self.frame_guides)
        self.label_dn.setObjectName("label_dn")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_dn)
        self.doubleSpinBox_dn = QtWidgets.QDoubleSpinBox(self.frame_guides)
        self.doubleSpinBox_dn.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.doubleSpinBox_dn.setDecimals(6)
        self.doubleSpinBox_dn.setMinimum(1e-06)
        self.doubleSpinBox_dn.setMaximum(1000.0)
        self.doubleSpinBox_dn.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.doubleSpinBox_dn.setProperty("value", 0.001)
        self.doubleSpinBox_dn.setObjectName("doubleSpinBox_dn")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_dn)
        self.radioButton_gaussian = QtWidgets.QRadioButton(self.frame_guides)
        self.radioButton_gaussian.setChecked(True)
        self.radioButton_gaussian.setObjectName("radioButton_gaussian")
        self.formLayout_6.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.radioButton_gaussian)
        self.spinBox_gauss_pow = QtWidgets.QSpinBox(self.frame_guides)
        self.spinBox_gauss_pow.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.spinBox_gauss_pow.setSuffix("")
        self.spinBox_gauss_pow.setMinimum(1)
        self.spinBox_gauss_pow.setMaximum(10)
        self.spinBox_gauss_pow.setSingleStep(1)
        self.spinBox_gauss_pow.setProperty("value", 4)
        self.spinBox_gauss_pow.setObjectName("spinBox_gauss_pow")
        self.formLayout_6.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.spinBox_gauss_pow)
        self.radioButton_squared = QtWidgets.QRadioButton(self.frame_guides)
        self.radioButton_squared.setObjectName("radioButton_squared")
        self.formLayout_6.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.radioButton_squared)
        self.verticalLayout_guide.addWidget(self.frame_guides)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_guide.addItem(spacerItem1)
        self.tabWidget_morphology_guide = QtWidgets.QTabWidget(self.tabWidget_guide)
        self.tabWidget_morphology_guide.setMinimumSize(QtCore.QSize(370, 0))
        self.tabWidget_morphology_guide.setMaximumSize(QtCore.QSize(370, 16777215))
        self.tabWidget_morphology_guide.setToolTip("")
        self.tabWidget_morphology_guide.setObjectName("tabWidget_morphology_guide")
        self.tab_array = QtWidgets.QWidget()
        self.tab_array.setObjectName("tab_array")
        self.formLayout = QtWidgets.QFormLayout(self.tab_array)
        self.formLayout.setObjectName("formLayout")
        self.label_nb_p = QtWidgets.QLabel(self.tab_array)
        self.label_nb_p.setObjectName("label_nb_p")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_nb_p)
        self.spinBox_nb_p = QtWidgets.QSpinBox(self.tab_array)
        self.spinBox_nb_p.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.spinBox_nb_p.setMaximum(1000)
        self.spinBox_nb_p.setProperty("value", 11)
        self.spinBox_nb_p.setObjectName("spinBox_nb_p")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_nb_p)
        self.label_p = QtWidgets.QLabel(self.tab_array)
        self.label_p.setObjectName("label_p")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_p)
        self.doubleSpinBox_p = QtWidgets.QDoubleSpinBox(self.tab_array)
        self.doubleSpinBox_p.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.doubleSpinBox_p.setDecimals(3)
        self.doubleSpinBox_p.setMaximum(10000.0)
        self.doubleSpinBox_p.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.doubleSpinBox_p.setProperty("value", 15.0)
        self.doubleSpinBox_p.setObjectName("doubleSpinBox_p")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_p)
        self.calculateButton_array = QtWidgets.QPushButton(self.tab_array)
        self.calculateButton_array.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.calculateButton_array.setObjectName("calculateButton_array")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.calculateButton_array)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.formLayout.setItem(2, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        self.tabWidget_morphology_guide.addTab(self.tab_array, "")
        self.tab_curved = QtWidgets.QWidget()
        self.tab_curved.setObjectName("tab_curved")
        self.formLayout_2 = QtWidgets.QFormLayout(self.tab_curved)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_curve = QtWidgets.QLabel(self.tab_curved)
        self.label_curve.setObjectName("label_curve")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_curve)
        self.doubleSpinBox_curve = QtWidgets.QDoubleSpinBox(self.tab_curved)
        self.doubleSpinBox_curve.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.doubleSpinBox_curve.setDecimals(3)
        self.doubleSpinBox_curve.setMinimum(-100000000.0)
        self.doubleSpinBox_curve.setMaximum(100000000.0)
        self.doubleSpinBox_curve.setProperty("value", 40.0)
        self.doubleSpinBox_curve.setObjectName("doubleSpinBox_curve")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_curve)
        self.label_half_delay = QtWidgets.QLabel(self.tab_curved)
        self.label_half_delay.setObjectName("label_half_delay")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_half_delay)
        self.doubleSpinBox_half_delay = QtWidgets.QDoubleSpinBox(self.tab_curved)
        self.doubleSpinBox_half_delay.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.doubleSpinBox_half_delay.setDecimals(3)
        self.doubleSpinBox_half_delay.setMaximum(100000.0)
        self.doubleSpinBox_half_delay.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.doubleSpinBox_half_delay.setProperty("value", 1000.0)
        self.doubleSpinBox_half_delay.setObjectName("doubleSpinBox_half_delay")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_half_delay)
        self.label_distance_factor = QtWidgets.QLabel(self.tab_curved)
        self.label_distance_factor.setObjectName("label_distance_factor")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_distance_factor)
        self.doubleSpinBox_distance_factor = QtWidgets.QDoubleSpinBox(self.tab_curved)
        self.doubleSpinBox_distance_factor.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.doubleSpinBox_distance_factor.setDecimals(3)
        self.doubleSpinBox_distance_factor.setMaximum(10000.0)
        self.doubleSpinBox_distance_factor.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.doubleSpinBox_distance_factor.setProperty("value", 1.2)
        self.doubleSpinBox_distance_factor.setObjectName("doubleSpinBox_distance_factor")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_distance_factor)
        self.calculateButton_curved = QtWidgets.QPushButton(self.tab_curved)
        self.calculateButton_curved.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.calculateButton_curved.setObjectName("calculateButton_curved")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.calculateButton_curved)
        self.tabWidget_morphology_guide.addTab(self.tab_curved, "")
        self.verticalLayout_guide.addWidget(self.tabWidget_morphology_guide)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_guide.addItem(spacerItem3)
        self.pushButton_cancel_guide = QtWidgets.QPushButton(self.tabWidget_guide)
        self.pushButton_cancel_guide.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_cancel_guide.setStatusTip("")
        self.pushButton_cancel_guide.setObjectName("pushButton_cancel_guide")
        self.verticalLayout_guide.addWidget(self.pushButton_cancel_guide)
        self.horizontalLayout_2.addLayout(self.verticalLayout_guide)
        self.plot_guide = QtWidgets.QVBoxLayout()
        self.plot_guide.setObjectName("plot_guide")
        self.horizontalLayout_2.addLayout(self.plot_guide)
        self.tabWidget_main.addTab(self.tabWidget_guide, "")
        self.tabWidget_light = QtWidgets.QWidget()
        self.tabWidget_light.setObjectName("tabWidget_light")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tabWidget_light)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_light = QtWidgets.QVBoxLayout()
        self.verticalLayout_light.setObjectName("verticalLayout_light")
        self.label_light_informations = QtWidgets.QLabel(self.tabWidget_light)
        self.label_light_informations.setMinimumSize(QtCore.QSize(0, 62))
        self.label_light_informations.setObjectName("label_light_informations")
        self.verticalLayout_light.addWidget(self.label_light_informations)
        self.frame_light = QtWidgets.QFrame(self.tabWidget_light)
        self.frame_light.setMaximumSize(QtCore.QSize(370, 16777215))
        self.frame_light.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_light.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_light.setObjectName("frame_light")
        self.formLayout_lo_theta = QtWidgets.QFormLayout(self.frame_light)
        self.formLayout_lo_theta.setObjectName("formLayout_lo_theta")
        self.label_lo = QtWidgets.QLabel(self.frame_light)
        self.label_lo.setObjectName("label_lo")
        self.formLayout_lo_theta.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_lo)
        self.doubleSpinBox_lo = QtWidgets.QDoubleSpinBox(self.frame_light)
        self.doubleSpinBox_lo.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.doubleSpinBox_lo.setDecimals(4)
        self.doubleSpinBox_lo.setMinimum(0.01)
        self.doubleSpinBox_lo.setMaximum(100.0)
        self.doubleSpinBox_lo.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.doubleSpinBox_lo.setProperty("value", 1.5)
        self.doubleSpinBox_lo.setObjectName("doubleSpinBox_lo")
        self.formLayout_lo_theta.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_lo)
        self.label_theta_ext = QtWidgets.QLabel(self.frame_light)
        self.label_theta_ext.setObjectName("label_theta_ext")
        self.formLayout_lo_theta.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_theta_ext)
        self.doubleSpinBox_theta_ext = QtWidgets.QDoubleSpinBox(self.frame_light)
        self.doubleSpinBox_theta_ext.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.doubleSpinBox_theta_ext.setMinimum(-90.0)
        self.doubleSpinBox_theta_ext.setMaximum(90.0)
        self.doubleSpinBox_theta_ext.setObjectName("doubleSpinBox_theta_ext")
        self.formLayout_lo_theta.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_theta_ext)
        self.verticalLayout_light.addWidget(self.frame_light)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_light.addItem(spacerItem4)
        self.frame_beam = QtWidgets.QFrame(self.tabWidget_light)
        self.frame_beam.setMaximumSize(QtCore.QSize(370, 16777215))
        self.frame_beam.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_beam.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_beam.setObjectName("frame_beam")
        self.formLayout_5 = QtWidgets.QFormLayout(self.frame_beam)
        self.formLayout_5.setObjectName("formLayout_5")
        self.comboBox_light = QtWidgets.QComboBox(self.frame_beam)
        self.comboBox_light.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBox_light.setObjectName("comboBox_light")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.comboBox_light)
        self.Qframe_beam_create = QtWidgets.QFrame(self.frame_beam)
        self.Qframe_beam_create.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Qframe_beam_create.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Qframe_beam_create.setObjectName("Qframe_beam_create")
        self.gridLayout_creat_delete_beam = QtWidgets.QGridLayout(self.Qframe_beam_create)
        self.gridLayout_creat_delete_beam.setObjectName("gridLayout_creat_delete_beam")
        self.pushButton_delete_beam = QtWidgets.QPushButton(self.Qframe_beam_create)
        self.pushButton_delete_beam.setObjectName("pushButton_delete_beam")
        self.gridLayout_creat_delete_beam.addWidget(self.pushButton_delete_beam, 2, 1, 1, 1)
        self.pushButton_create_beam = QtWidgets.QPushButton(self.Qframe_beam_create)
        self.pushButton_create_beam.setObjectName("pushButton_create_beam")
        self.gridLayout_creat_delete_beam.addWidget(self.pushButton_create_beam, 2, 0, 1, 1)
        self.pushButton_save_beam = QtWidgets.QPushButton(self.Qframe_beam_create)
        self.pushButton_save_beam.setObjectName("pushButton_save_beam")
        self.gridLayout_creat_delete_beam.addWidget(self.pushButton_save_beam, 3, 0, 1, 1)
        self.pushButton_cancel_light = QtWidgets.QPushButton(self.Qframe_beam_create)
        self.pushButton_cancel_light.setObjectName("pushButton_cancel_light")
        self.gridLayout_creat_delete_beam.addWidget(self.pushButton_cancel_light, 3, 1, 1, 1)
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.Qframe_beam_create)
        self.label_fwhm = QtWidgets.QLabel(self.frame_beam)
        self.label_fwhm.setObjectName("label_fwhm")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_fwhm)
        self.doubleSpinBox_fwhm = QtWidgets.QDoubleSpinBox(self.frame_beam)
        self.doubleSpinBox_fwhm.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.doubleSpinBox_fwhm.setDecimals(3)
        self.doubleSpinBox_fwhm.setMaximum(10000.0)
        self.doubleSpinBox_fwhm.setProperty("value", 8.0)
        self.doubleSpinBox_fwhm.setObjectName("doubleSpinBox_fwhm")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_fwhm)
        self.checkBox_offset_light = QtWidgets.QCheckBox(self.frame_beam)
        self.checkBox_offset_light.setChecked(True)
        self.checkBox_offset_light.setObjectName("checkBox_offset_light")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.checkBox_offset_light)
        self.spinBox_offset_light_peak = QtWidgets.QSpinBox(self.frame_beam)
        self.spinBox_offset_light_peak.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.spinBox_offset_light_peak.setSuffix("")
        self.spinBox_offset_light_peak.setMaximum(10000)
        self.spinBox_offset_light_peak.setProperty("value", 5)
        self.spinBox_offset_light_peak.setObjectName("spinBox_offset_light_peak")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBox_offset_light_peak)
        self.label_offset_light = QtWidgets.QLabel(self.frame_beam)
        self.label_offset_light.setObjectName("label_offset_light")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_offset_light)
        self.doubleSpinBox_offset_light = QtWidgets.QDoubleSpinBox(self.frame_beam)
        self.doubleSpinBox_offset_light.setEnabled(False)
        self.doubleSpinBox_offset_light.setMinimum(-10000.0)
        self.doubleSpinBox_offset_light.setMaximum(10000.0)
        self.doubleSpinBox_offset_light.setObjectName("doubleSpinBox_offset_light")
        self.formLayout_5.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_offset_light)
        self.label_intensity = QtWidgets.QLabel(self.frame_beam)
        self.label_intensity.setObjectName("label_intensity")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_intensity)
        self.doubleSpinBox_intensity_light = QtWidgets.QDoubleSpinBox(self.frame_beam)
        self.doubleSpinBox_intensity_light.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.doubleSpinBox_intensity_light.setDecimals(5)
        self.doubleSpinBox_intensity_light.setMaximum(10000.0)
        self.doubleSpinBox_intensity_light.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.doubleSpinBox_intensity_light.setProperty("value", 1.0)
        self.doubleSpinBox_intensity_light.setObjectName("doubleSpinBox_intensity_light")
        self.formLayout_5.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_intensity_light)
        self.radioButton_gaussian_light = QtWidgets.QRadioButton(self.frame_beam)
        self.radioButton_gaussian_light.setEnabled(True)
        self.radioButton_gaussian_light.setChecked(True)
        self.radioButton_gaussian_light.setObjectName("radioButton_gaussian_light")
        self.formLayout_5.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.radioButton_gaussian_light)
        self.radioButton_squared_light = QtWidgets.QRadioButton(self.frame_beam)
        self.radioButton_squared_light.setChecked(False)
        self.radioButton_squared_light.setObjectName("radioButton_squared_light")
        self.formLayout_5.setWidget(10, QtWidgets.QFormLayout.SpanningRole, self.radioButton_squared_light)
        self.radioButton_mode = QtWidgets.QRadioButton(self.frame_beam)
        self.radioButton_mode.setObjectName("radioButton_mode")
        self.formLayout_5.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.radioButton_mode)
        self.spinBox_mode = QtWidgets.QSpinBox(self.frame_beam)
        self.spinBox_mode.setAutoFillBackground(False)
        self.spinBox_mode.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.spinBox_mode.setMaximum(50)
        self.spinBox_mode.setObjectName("spinBox_mode")
        self.formLayout_5.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.spinBox_mode)
        self.radioButton_all_modes = QtWidgets.QRadioButton(self.frame_beam)
        self.radioButton_all_modes.setObjectName("radioButton_all_modes")
        self.formLayout_5.setWidget(16, QtWidgets.QFormLayout.LabelRole, self.radioButton_all_modes)
        self.radioButton_airy = QtWidgets.QRadioButton(self.frame_beam)
        self.radioButton_airy.setObjectName("radioButton_airy")
        self.formLayout_5.setWidget(19, QtWidgets.QFormLayout.LabelRole, self.radioButton_airy)
        self.label_zero_cut = QtWidgets.QLabel(self.frame_beam)
        self.label_zero_cut.setObjectName("label_zero_cut")
        self.formLayout_5.setWidget(20, QtWidgets.QFormLayout.LabelRole, self.label_zero_cut)
        self.spinBox_airy_zero = QtWidgets.QSpinBox(self.frame_beam)
        self.spinBox_airy_zero.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.spinBox_airy_zero.setMinimum(1)
        self.spinBox_airy_zero.setMaximum(10000)
        self.spinBox_airy_zero.setProperty("value", 10)
        self.spinBox_airy_zero.setObjectName("spinBox_airy_zero")
        self.formLayout_5.setWidget(20, QtWidgets.QFormLayout.FieldRole, self.spinBox_airy_zero)
        self.label_lobe_size = QtWidgets.QLabel(self.frame_beam)
        self.label_lobe_size.setObjectName("label_lobe_size")
        self.formLayout_5.setWidget(21, QtWidgets.QFormLayout.LabelRole, self.label_lobe_size)
        self.doubleSpinBox_lobe_size = QtWidgets.QDoubleSpinBox(self.frame_beam)
        self.doubleSpinBox_lobe_size.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.doubleSpinBox_lobe_size.setMaximum(10000.0)
        self.doubleSpinBox_lobe_size.setProperty("value", 8.0)
        self.doubleSpinBox_lobe_size.setObjectName("doubleSpinBox_lobe_size")
        self.formLayout_5.setWidget(21, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_lobe_size)
        spacerItem5 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_5.setItem(18, QtWidgets.QFormLayout.LabelRole, spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_5.setItem(12, QtWidgets.QFormLayout.LabelRole, spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_5.setItem(7, QtWidgets.QFormLayout.LabelRole, spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_5.setItem(15, QtWidgets.QFormLayout.LabelRole, spacerItem8)
        self.pushButton_mode_number = QtWidgets.QPushButton(self.frame_beam)
        self.pushButton_mode_number.setObjectName("pushButton_mode_number")
        self.formLayout_5.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.pushButton_mode_number)
        self.mode_number = QtWidgets.QLCDNumber(self.frame_beam)
        self.mode_number.setMaximumSize(QtCore.QSize(100, 16777215))
        self.mode_number.setObjectName("mode_number")
        self.formLayout_5.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.mode_number)
        spacerItem9 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.formLayout_5.setItem(9, QtWidgets.QFormLayout.LabelRole, spacerItem9)
        self.verticalLayout_light.addWidget(self.frame_beam)
        spacerItem10 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_light.addItem(spacerItem10)
        self.calculateButton_light = QtWidgets.QPushButton(self.tabWidget_light)
        self.calculateButton_light.setMaximumSize(QtCore.QSize(370, 16777215))
        self.calculateButton_light.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.calculateButton_light.setObjectName("calculateButton_light")
        self.verticalLayout_light.addWidget(self.calculateButton_light)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_light.addItem(spacerItem11)
        self.horizontalLayout_4.addLayout(self.verticalLayout_light)
        self.plot_light = QtWidgets.QVBoxLayout()
        self.plot_light.setObjectName("plot_light")
        self.horizontalLayout_4.addLayout(self.plot_light)
        self.tabWidget_main.addTab(self.tabWidget_light, "")
        self.tabWidget_compute = QtWidgets.QWidget()
        self.tabWidget_compute.setObjectName("tabWidget_compute")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tabWidget_compute)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_compute_plot = QtWidgets.QVBoxLayout()
        self.verticalLayout_compute_plot.setObjectName("verticalLayout_compute_plot")
        self.verticalLayout_compute = QtWidgets.QVBoxLayout()
        self.verticalLayout_compute.setObjectName("verticalLayout_compute")
        self.label_lost_informations = QtWidgets.QLabel(self.tabWidget_compute)
        self.label_lost_informations.setMinimumSize(QtCore.QSize(0, 62))
        self.label_lost_informations.setMouseTracking(True)
        self.label_lost_informations.setObjectName("label_lost_informations")
        self.verticalLayout_compute.addWidget(self.label_lost_informations)
        self.checkBox_lost = QtWidgets.QCheckBox(self.tabWidget_compute)
        self.checkBox_lost.setEnabled(True)
        self.checkBox_lost.setCheckable(True)
        self.checkBox_lost.setChecked(False)
        self.checkBox_lost.setObjectName("checkBox_lost")
        self.verticalLayout_compute.addWidget(self.checkBox_lost)
        self.frame_lost = QtWidgets.QFrame(self.tabWidget_compute)
        self.frame_lost.setEnabled(False)
        self.frame_lost.setMinimumSize(QtCore.QSize(370, 0))
        self.frame_lost.setMaximumSize(QtCore.QSize(370, 16777215))
        self.frame_lost.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_lost.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_lost.setObjectName("frame_lost")
        self.formLayout_8 = QtWidgets.QFormLayout(self.frame_lost)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_guide_lost = QtWidgets.QLabel(self.frame_lost)
        self.label_guide_lost.setObjectName("label_guide_lost")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_guide_lost)
        self.spinBox_guide_lost = QtWidgets.QSpinBox(self.frame_lost)
        self.spinBox_guide_lost.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.spinBox_guide_lost.setMaximum(1000)
        self.spinBox_guide_lost.setObjectName("spinBox_guide_lost")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_guide_lost)
        self.label_width_lost = QtWidgets.QLabel(self.frame_lost)
        self.label_width_lost.setObjectName("label_width_lost")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_width_lost)
        self.doubleSpinBox_width_lost = QtWidgets.QDoubleSpinBox(self.frame_lost)
        self.doubleSpinBox_width_lost.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.doubleSpinBox_width_lost.setDecimals(3)
        self.doubleSpinBox_width_lost.setMaximum(10000.0)
        self.doubleSpinBox_width_lost.setProperty("value", 10.0)
        self.doubleSpinBox_width_lost.setObjectName("doubleSpinBox_width_lost")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_width_lost)
        self.label_lost = QtWidgets.QLabel(self.frame_lost)
        self.label_lost.setObjectName("label_lost")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_lost)
        self.doubleSpinBox_lost = QtWidgets.QDoubleSpinBox(self.frame_lost)
        self.doubleSpinBox_lost.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.doubleSpinBox_lost.setDecimals(5)
        self.doubleSpinBox_lost.setMaximum(10000.0)
        self.doubleSpinBox_lost.setStepType(QtWidgets.QAbstractSpinBox.AdaptiveDecimalStepType)
        self.doubleSpinBox_lost.setProperty("value", 1.0)
        self.doubleSpinBox_lost.setObjectName("doubleSpinBox_lost")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_lost)
        self.verticalLayout_compute.addWidget(self.frame_lost)
        spacerItem12 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_compute.addItem(spacerItem12)
        self.label_kerr_informations = QtWidgets.QLabel(self.tabWidget_compute)
        self.label_kerr_informations.setMinimumSize(QtCore.QSize(0, 62))
        self.label_kerr_informations.setMouseTracking(True)
        self.label_kerr_informations.setObjectName("label_kerr_informations")
        self.verticalLayout_compute.addWidget(self.label_kerr_informations)
        self.checkBox_kerr = QtWidgets.QCheckBox(self.tabWidget_compute)
        self.checkBox_kerr.setEnabled(True)
        self.checkBox_kerr.setChecked(False)
        self.checkBox_kerr.setObjectName("checkBox_kerr")
        self.verticalLayout_compute.addWidget(self.checkBox_kerr)
        self.frame_kerr = QtWidgets.QFrame(self.tabWidget_compute)
        self.frame_kerr.setEnabled(False)
        self.frame_kerr.setMinimumSize(QtCore.QSize(370, 0))
        self.frame_kerr.setMaximumSize(QtCore.QSize(370, 16777215))
        self.frame_kerr.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_kerr.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_kerr.setObjectName("frame_kerr")
        self.formLayout_9 = QtWidgets.QFormLayout(self.frame_kerr)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_correction_loop = QtWidgets.QLabel(self.frame_kerr)
        self.label_correction_loop.setObjectName("label_correction_loop")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_correction_loop)
        self.spinBox_kerr_loop = QtWidgets.QSpinBox(self.frame_kerr)
        self.spinBox_kerr_loop.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.spinBox_kerr_loop.setMinimum(1)
        self.spinBox_kerr_loop.setMaximum(100)
        self.spinBox_kerr_loop.setProperty("value", 2)
        self.spinBox_kerr_loop.setObjectName("spinBox_kerr_loop")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_kerr_loop)
        self.label_chi3 = QtWidgets.QLabel(self.frame_kerr)
        self.label_chi3.setObjectName("label_chi3")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_chi3)
        self.doubleSpinBox_chi3 = QtWidgets.QDoubleSpinBox(self.frame_kerr)
        self.doubleSpinBox_chi3.setCorrectionMode(QtWidgets.QAbstractSpinBox.CorrectToNearestValue)
        self.doubleSpinBox_chi3.setMaximum(100000.0)
        self.doubleSpinBox_chi3.setProperty("value", 10.0)
        self.doubleSpinBox_chi3.setObjectName("doubleSpinBox_chi3")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_chi3)
        self.checkBox_variance = QtWidgets.QCheckBox(self.frame_kerr)
        self.checkBox_variance.setEnabled(False)
        self.checkBox_variance.setObjectName("checkBox_variance")
        self.formLayout_9.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.checkBox_variance)
        self.verticalLayout_compute.addWidget(self.frame_kerr)
        self.formLayout_estimate = QtWidgets.QFormLayout()
        self.formLayout_estimate.setObjectName("formLayout_estimate")
        self.estimate_time_display = QtWidgets.QLCDNumber(self.tabWidget_compute)
        self.estimate_time_display.setEnabled(True)
        self.estimate_time_display.setMinimumSize(QtCore.QSize(100, 0))
        self.estimate_time_display.setMaximumSize(QtCore.QSize(100, 16777215))
        self.estimate_time_display.setDigitCount(3)
        self.estimate_time_display.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.estimate_time_display.setObjectName("estimate_time_display")
        self.formLayout_estimate.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.estimate_time_display)
        self.pushButton_estimate_time = QtWidgets.QPushButton(self.tabWidget_compute)
        self.pushButton_estimate_time.setMinimumSize(QtCore.QSize(150, 0))
        self.pushButton_estimate_time.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton_estimate_time.setObjectName("pushButton_estimate_time")
        self.formLayout_estimate.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton_estimate_time)
        self.verticalLayout_compute.addLayout(self.formLayout_estimate)
        spacerItem13 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_compute.addItem(spacerItem13)
        self.calculateButton_compute = QtWidgets.QPushButton(self.tabWidget_compute)
        self.calculateButton_compute.setMinimumSize(QtCore.QSize(370, 0))
        self.calculateButton_compute.setMaximumSize(QtCore.QSize(370, 16777215))
        self.calculateButton_compute.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.calculateButton_compute.setObjectName("calculateButton_compute")
        self.verticalLayout_compute.addWidget(self.calculateButton_compute)
        self.checkBox_check_power = QtWidgets.QCheckBox(self.tabWidget_compute)
        self.checkBox_check_power.setObjectName("checkBox_check_power")
        self.verticalLayout_compute.addWidget(self.checkBox_check_power)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_compute.addItem(spacerItem14)
        self.verticalLayout_compute_plot.addLayout(self.verticalLayout_compute)
        self.pushButton_cancel_compute = QtWidgets.QPushButton(self.tabWidget_compute)
        self.pushButton_cancel_compute.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_cancel_compute.setObjectName("pushButton_cancel_compute")
        self.verticalLayout_compute_plot.addWidget(self.pushButton_cancel_compute)
        self.horizontalLayout.addLayout(self.verticalLayout_compute_plot)
        self.plot_compute = QtWidgets.QVBoxLayout()
        self.plot_compute.setObjectName("plot_compute")
        self.horizontalLayout.addLayout(self.plot_compute)
        self.tabWidget_main.addTab(self.tabWidget_compute, "")
        self.verticalLayout.addWidget(self.tabWidget_main)
        self.gridLayout.addWidget(self.frame_file_data, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.label_length.setBuddy(self.frame_light)

        self.retranslateUi(MainWindow)
        self.tabWidget_main.setCurrentIndex(0)
        self.tabWidget_morphology_guide.setCurrentIndex(0)
        self.checkBox_offset_light.clicked['bool'].connect(self.doubleSpinBox_offset_light.setDisabled)
        self.checkBox_kerr.clicked['bool'].connect(self.frame_kerr.setEnabled)
        self.checkBox_offset_light.clicked['bool'].connect(self.spinBox_offset_light_peak.setEnabled)
        self.checkBox_lost.clicked['bool'].connect(self.frame_lost.setEnabled)
        self.checkBox_kerr.clicked['bool'].connect(self.checkBox_variance.setEnabled)
        self.comboBox_light.activated['QString'].connect(self.pushButton_cancel_light.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget_main, self.doubleSpinBox_length_z)
        MainWindow.setTabOrder(self.doubleSpinBox_length_z, self.doubleSpinBox_dist_z)
        MainWindow.setTabOrder(self.doubleSpinBox_dist_z, self.spinBox_nbr_z_disp)
        MainWindow.setTabOrder(self.spinBox_nbr_z_disp, self.doubleSpinBox_length_x)
        MainWindow.setTabOrder(self.doubleSpinBox_length_x, self.doubleSpinBox_dist_x)
        MainWindow.setTabOrder(self.doubleSpinBox_dist_x, self.doubleSpinBox_width)
        MainWindow.setTabOrder(self.doubleSpinBox_width, self.doubleSpinBox_offset_guide)
        MainWindow.setTabOrder(self.doubleSpinBox_offset_guide, self.doubleSpinBox_n)
        MainWindow.setTabOrder(self.doubleSpinBox_n, self.doubleSpinBox_dn)
        MainWindow.setTabOrder(self.doubleSpinBox_dn, self.radioButton_gaussian)
        MainWindow.setTabOrder(self.radioButton_gaussian, self.spinBox_gauss_pow)
        MainWindow.setTabOrder(self.spinBox_gauss_pow, self.radioButton_squared)
        MainWindow.setTabOrder(self.radioButton_squared, self.tabWidget_morphology_guide)
        MainWindow.setTabOrder(self.tabWidget_morphology_guide, self.spinBox_nb_p)
        MainWindow.setTabOrder(self.spinBox_nb_p, self.doubleSpinBox_p)
        MainWindow.setTabOrder(self.doubleSpinBox_p, self.calculateButton_array)
        MainWindow.setTabOrder(self.calculateButton_array, self.doubleSpinBox_curve)
        MainWindow.setTabOrder(self.doubleSpinBox_curve, self.doubleSpinBox_half_delay)
        MainWindow.setTabOrder(self.doubleSpinBox_half_delay, self.doubleSpinBox_distance_factor)
        MainWindow.setTabOrder(self.doubleSpinBox_distance_factor, self.calculateButton_curved)
        MainWindow.setTabOrder(self.calculateButton_curved, self.pushButton_cancel_guide)
        MainWindow.setTabOrder(self.pushButton_cancel_guide, self.doubleSpinBox_lo)
        MainWindow.setTabOrder(self.doubleSpinBox_lo, self.doubleSpinBox_theta_ext)
        MainWindow.setTabOrder(self.doubleSpinBox_theta_ext, self.comboBox_light)
        MainWindow.setTabOrder(self.comboBox_light, self.pushButton_create_beam)
        MainWindow.setTabOrder(self.pushButton_create_beam, self.pushButton_delete_beam)
        MainWindow.setTabOrder(self.pushButton_delete_beam, self.pushButton_save_beam)
        MainWindow.setTabOrder(self.pushButton_save_beam, self.pushButton_cancel_light)
        MainWindow.setTabOrder(self.pushButton_cancel_light, self.doubleSpinBox_fwhm)
        MainWindow.setTabOrder(self.doubleSpinBox_fwhm, self.checkBox_offset_light)
        MainWindow.setTabOrder(self.checkBox_offset_light, self.spinBox_offset_light_peak)
        MainWindow.setTabOrder(self.spinBox_offset_light_peak, self.doubleSpinBox_offset_light)
        MainWindow.setTabOrder(self.doubleSpinBox_offset_light, self.doubleSpinBox_intensity_light)
        MainWindow.setTabOrder(self.doubleSpinBox_intensity_light, self.radioButton_gaussian_light)
        MainWindow.setTabOrder(self.radioButton_gaussian_light, self.radioButton_squared_light)
        MainWindow.setTabOrder(self.radioButton_squared_light, self.radioButton_mode)
        MainWindow.setTabOrder(self.radioButton_mode, self.spinBox_mode)
        MainWindow.setTabOrder(self.spinBox_mode, self.pushButton_mode_number)
        MainWindow.setTabOrder(self.pushButton_mode_number, self.radioButton_all_modes)
        MainWindow.setTabOrder(self.radioButton_all_modes, self.radioButton_airy)
        MainWindow.setTabOrder(self.radioButton_airy, self.spinBox_airy_zero)
        MainWindow.setTabOrder(self.spinBox_airy_zero, self.doubleSpinBox_lobe_size)
        MainWindow.setTabOrder(self.doubleSpinBox_lobe_size, self.calculateButton_light)
        MainWindow.setTabOrder(self.calculateButton_light, self.checkBox_lost)
        MainWindow.setTabOrder(self.checkBox_lost, self.spinBox_guide_lost)
        MainWindow.setTabOrder(self.spinBox_guide_lost, self.doubleSpinBox_width_lost)
        MainWindow.setTabOrder(self.doubleSpinBox_width_lost, self.doubleSpinBox_lost)
        MainWindow.setTabOrder(self.doubleSpinBox_lost, self.checkBox_kerr)
        MainWindow.setTabOrder(self.checkBox_kerr, self.spinBox_kerr_loop)
        MainWindow.setTabOrder(self.spinBox_kerr_loop, self.doubleSpinBox_chi3)
        MainWindow.setTabOrder(self.doubleSpinBox_chi3, self.checkBox_variance)
        MainWindow.setTabOrder(self.checkBox_variance, self.pushButton_estimate_time)
        MainWindow.setTabOrder(self.pushButton_estimate_time, self.calculateButton_compute)
        MainWindow.setTabOrder(self.calculateButton_compute, self.checkBox_check_power)
        MainWindow.setTabOrder(self.checkBox_check_power, self.pushButton_cancel_compute)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Beampy"))
        self.label_window_parameters.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Window information</span></p></body></html>"))
        self.label_length.setToolTip(_translate("MainWindow", "Size of the computed window over z"))
        self.label_length.setText(_translate("MainWindow", "z length"))
        self.doubleSpinBox_length_z.setToolTip(_translate("MainWindow", "Size of the computed window over z"))
        self.doubleSpinBox_length_z.setSuffix(_translate("MainWindow", " µm"))
        self.label_dist_z.setToolTip(_translate("MainWindow", "Step over z in µm"))
        self.label_dist_z.setText(_translate("MainWindow", "z step"))
        self.doubleSpinBox_dist_z.setToolTip(_translate("MainWindow", "Step over z in µm"))
        self.doubleSpinBox_dist_z.setSuffix(_translate("MainWindow", " µm"))
        self.label_nbr_z_disp.setToolTip(_translate("MainWindow", "Number of points to display over z"))
        self.label_nbr_z_disp.setText(_translate("MainWindow", "z nbr displayed"))
        self.spinBox_nbr_z_disp.setToolTip(_translate("MainWindow", "Number of points to display over z"))
        self.label_length_x.setToolTip(_translate("MainWindow", "Size of the compute window over x in µm"))
        self.label_length_x.setText(_translate("MainWindow", "x length"))
        self.doubleSpinBox_length_x.setToolTip(_translate("MainWindow", "Size of the compute window over x in µm"))
        self.doubleSpinBox_length_x.setSuffix(_translate("MainWindow", " µm"))
        self.label_dist_x.setToolTip(_translate("MainWindow", "Step over x in µm"))
        self.label_dist_x.setText(_translate("MainWindow", "x step"))
        self.doubleSpinBox_dist_x.setToolTip(_translate("MainWindow", "Step over x in µm"))
        self.doubleSpinBox_dist_x.setSuffix(_translate("MainWindow", " µm"))
        self.label_guides_information.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Guides information</span></p></body></html>"))
        self.label_width.setToolTip(_translate("MainWindow", "Guide width define as the diameter in µm at 1/e"))
        self.label_width.setText(_translate("MainWindow", "Width"))
        self.doubleSpinBox_width.setToolTip(_translate("MainWindow", "Guide width define as the diameter in µm at 1/e"))
        self.doubleSpinBox_width.setSuffix(_translate("MainWindow", " μm"))
        self.label_offset_guide.setToolTip(_translate("MainWindow", "Guide offset from the center in µm"))
        self.label_offset_guide.setText(_translate("MainWindow", "Guide offset"))
        self.doubleSpinBox_offset_guide.setToolTip(_translate("MainWindow", "Guide offset from the center in µm"))
        self.doubleSpinBox_offset_guide.setSuffix(_translate("MainWindow", " µm"))
        self.doubleSpinBox_n.setToolTip(_translate("MainWindow", "Refractive index of the cladding"))
        self.label_n.setToolTip(_translate("MainWindow", "Refractive index of the cladding"))
        self.label_n.setText(_translate("MainWindow", "n"))
        self.label_dn.setToolTip(_translate("MainWindow", "Difference of refractive index between the core and the cladding"))
        self.label_dn.setText(_translate("MainWindow", "Δn"))
        self.doubleSpinBox_dn.setToolTip(_translate("MainWindow", "Difference of refractive index between the core and the cladding"))
        self.radioButton_gaussian.setToolTip(_translate("MainWindow", "Choose super-gaussian guides"))
        self.radioButton_gaussian.setText(_translate("MainWindow", "Gaussian"))
        self.spinBox_gauss_pow.setToolTip(_translate("MainWindow", "Order of the super-Gaussian beam, 1 is gaussian, 4 is the usual super-Gaussian"))
        self.spinBox_gauss_pow.setPrefix(_translate("MainWindow", "order: "))
        self.radioButton_squared.setToolTip(_translate("MainWindow", "Choose squared guides"))
        self.radioButton_squared.setText(_translate("MainWindow", "Squared"))
        self.label_nb_p.setToolTip(_translate("MainWindow", "Number of guides"))
        self.label_nb_p.setText(_translate("MainWindow", "Numbers of guides"))
        self.spinBox_nb_p.setToolTip(_translate("MainWindow", "Number of guides"))
        self.label_p.setToolTip(_translate("MainWindow", "Distance between two guides center in µm"))
        self.label_p.setText(_translate("MainWindow", "Interval between guides"))
        self.doubleSpinBox_p.setToolTip(_translate("MainWindow", "Distance between two guides center in µm"))
        self.doubleSpinBox_p.setSuffix(_translate("MainWindow", " µm"))
        self.calculateButton_array.setToolTip(_translate("MainWindow", "Compute an array of guides"))
        self.calculateButton_array.setText(_translate("MainWindow", "Compute array of guides"))
        self.tabWidget_morphology_guide.setTabText(self.tabWidget_morphology_guide.indexOf(self.tab_array), _translate("MainWindow", "waveguide array"))
        self.label_curve.setToolTip(_translate("MainWindow", "curvature factor in 10^-8 1/µm^2"))
        self.label_curve.setText(_translate("MainWindow", "Curvature"))
        self.doubleSpinBox_curve.setToolTip(_translate("MainWindow", "curvature factor in 10^-8 1/µm^2"))
        self.doubleSpinBox_curve.setSuffix(_translate("MainWindow", " * 10^-8 1/µm^2"))
        self.label_half_delay.setToolTip(_translate("MainWindow", "Half distance over z in µm bewteen the two external guides where they are the closest"))
        self.label_half_delay.setText(_translate("MainWindow", "Half delay"))
        self.doubleSpinBox_half_delay.setToolTip(_translate("MainWindow", "Half distance over z in µm bewteen the two external guides where they are the closest"))
        self.doubleSpinBox_half_delay.setSuffix(_translate("MainWindow", " µm"))
        self.label_distance_factor.setToolTip(_translate("MainWindow", "Distance factor: p_min/width"))
        self.label_distance_factor.setText(_translate("MainWindow", "p_min/width"))
        self.doubleSpinBox_distance_factor.setToolTip(_translate("MainWindow", "Distance factor: p_min/width"))
        self.doubleSpinBox_distance_factor.setSuffix(_translate("MainWindow", " µm"))
        self.calculateButton_curved.setToolTip(_translate("MainWindow", "Compute the curved guides define as : - offset_guide + curve*(z - length_z/2 - half_delay)**2 + width*distance_factor)"))
        self.calculateButton_curved.setText(_translate("MainWindow", "Compute curved guides"))
        self.tabWidget_morphology_guide.setTabText(self.tabWidget_morphology_guide.indexOf(self.tab_curved), _translate("MainWindow", "curved waveguides"))
        self.pushButton_cancel_guide.setToolTip(_translate("MainWindow", "cancel guide changes"))
        self.pushButton_cancel_guide.setText(_translate("MainWindow", "Cancel changes"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tabWidget_guide), _translate("MainWindow", "Guides"))
        self.label_light_informations.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Light information</span></p></body></html>"))
        self.label_lo.setToolTip(_translate("MainWindow", " Wavelengh in µm"))
        self.label_lo.setText(_translate("MainWindow", "λ"))
        self.doubleSpinBox_lo.setToolTip(_translate("MainWindow", " Wavelengh in µm"))
        self.doubleSpinBox_lo.setSuffix(_translate("MainWindow", " µm"))
        self.label_theta_ext.setToolTip(_translate("MainWindow", "Number of the last mode that can propagate in the guide"))
        self.label_theta_ext.setText(_translate("MainWindow", "θ ext"))
        self.doubleSpinBox_theta_ext.setToolTip(_translate("MainWindow", "Exterior inclinaison angle in ° define from a interface between air and the cladding"))
        self.doubleSpinBox_theta_ext.setSuffix(_translate("MainWindow", " °"))
        self.comboBox_light.setToolTip(_translate("MainWindow", "Select the beam"))
        self.pushButton_delete_beam.setToolTip(_translate("MainWindow", "Delete the current displayed beam"))
        self.pushButton_delete_beam.setText(_translate("MainWindow", "delete beam"))
        self.pushButton_create_beam.setToolTip(_translate("MainWindow", "Add a new beam with current displayed values"))
        self.pushButton_create_beam.setText(_translate("MainWindow", "create beam"))
        self.pushButton_save_beam.setToolTip(_translate("MainWindow", "Save current displayed values"))
        self.pushButton_save_beam.setText(_translate("MainWindow", "save beam"))
        self.pushButton_cancel_light.setToolTip(_translate("MainWindow", "Return to previously saved values"))
        self.pushButton_cancel_light.setText(_translate("MainWindow", "cancel changes"))
        self.label_fwhm.setToolTip(_translate("MainWindow", "Full width at half maximum (for intensity not amplitude)"))
        self.label_fwhm.setText(_translate("MainWindow", "FWHM"))
        self.doubleSpinBox_fwhm.setToolTip(_translate("MainWindow", "Full width at half maximum (for intensity not amplitude)"))
        self.doubleSpinBox_fwhm.setSuffix(_translate("MainWindow", " μm"))
        self.checkBox_offset_light.setToolTip(_translate("MainWindow", "Choose if offset is define by the guides positions or by the distance from center"))
        self.checkBox_offset_light.setText(_translate("MainWindow", "Offset (number)"))
        self.spinBox_offset_light_peak.setToolTip(_translate("MainWindow", "Offset define by the guide position"))
        self.spinBox_offset_light_peak.setPrefix(_translate("MainWindow", "Guide number : "))
        self.label_offset_light.setToolTip(_translate("MainWindow", "Light offset from center"))
        self.label_offset_light.setText(_translate("MainWindow", "Offset (µm)"))
        self.doubleSpinBox_offset_light.setToolTip(_translate("MainWindow", "Light offset from center in µm"))
        self.doubleSpinBox_offset_light.setSuffix(_translate("MainWindow", " µm"))
        self.label_intensity.setToolTip(_translate("MainWindow", "Beam power"))
        self.label_intensity.setText(_translate("MainWindow", "Beam power"))
        self.doubleSpinBox_intensity_light.setToolTip(_translate("MainWindow", "Beam power |E|^2 in GW/cm^2"))
        self.doubleSpinBox_intensity_light.setSuffix(_translate("MainWindow", " GW/cm^2"))
        self.radioButton_gaussian_light.setToolTip(_translate("MainWindow", "Select a gaussian beam"))
        self.radioButton_gaussian_light.setText(_translate("MainWindow", "Gaussian"))
        self.radioButton_squared_light.setToolTip(_translate("MainWindow", "Select a squared beam"))
        self.radioButton_squared_light.setText(_translate("MainWindow", "Squared"))
        self.radioButton_mode.setToolTip(_translate("MainWindow", "select the n mode based on a squared guide"))
        self.radioButton_mode.setText(_translate("MainWindow", "Mode"))
        self.spinBox_mode.setToolTip(_translate("MainWindow", "The n mode based on a squared guide"))
        self.radioButton_all_modes.setToolTip(_translate("MainWindow", "Select all possible modes for a squared guide"))
        self.radioButton_all_modes.setText(_translate("MainWindow", "All modes"))
        self.radioButton_airy.setToolTip(_translate("MainWindow", "Select a Airy beam"))
        self.radioButton_airy.setText(_translate("MainWindow", "Airy"))
        self.label_zero_cut.setToolTip(_translate("MainWindow", "Choose to cut at the n zero of the Airy function"))
        self.label_zero_cut.setText(_translate("MainWindow", "Zero cut"))
        self.spinBox_airy_zero.setToolTip(_translate("MainWindow", "Choose to cut at the n zero of the Airy function"))
        self.label_lobe_size.setText(_translate("MainWindow", "First lobe size"))
        self.doubleSpinBox_lobe_size.setSuffix(_translate("MainWindow", " µm"))
        self.pushButton_mode_number.setToolTip(_translate("MainWindow", "Displayed the number of the last mode that can propagate in the rectangular guide"))
        self.pushButton_mode_number.setText(_translate("MainWindow", "Show max mode"))
        self.mode_number.setToolTip(_translate("MainWindow", "Number of the last mode that can propagate in the guide"))
        self.calculateButton_light.setToolTip(_translate("MainWindow", "Compute the beams"))
        self.calculateButton_light.setText(_translate("MainWindow", "Compute light"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tabWidget_light), _translate("MainWindow", "Light"))
        self.label_lost_informations.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Loss information</span></p></body></html>"))
        self.checkBox_lost.setToolTip(_translate("MainWindow", "Activate looses in guides"))
        self.checkBox_lost.setText(_translate("MainWindow", "activate looses"))
        self.label_guide_lost.setToolTip(_translate("MainWindow", "Guide number where looses occure"))
        self.label_guide_lost.setText(_translate("MainWindow", "Lost position"))
        self.spinBox_guide_lost.setToolTip(_translate("MainWindow", "Guide number where looses occure"))
        self.label_width_lost.setToolTip(_translate("MainWindow", "Interval where looses occures centered on the guide"))
        self.label_width_lost.setText(_translate("MainWindow", "Lost width"))
        self.doubleSpinBox_width_lost.setToolTip(_translate("MainWindow", "Interval where looses occures centered on the guide"))
        self.doubleSpinBox_width_lost.setSuffix(_translate("MainWindow", " µm"))
        self.label_lost.setToolTip(_translate("MainWindow", "Looses over z in 1/mm define as exp(-alpha * dist_z)"))
        self.label_lost.setText(_translate("MainWindow", "Lost value"))
        self.doubleSpinBox_lost.setToolTip(_translate("MainWindow", "Looses over z in 1/mm define as exp(-alpha * dist_z)"))
        self.doubleSpinBox_lost.setSuffix(_translate("MainWindow", " 1/mm"))
        self.label_kerr_informations.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Kerr information</span></p></body></html>"))
        self.checkBox_kerr.setToolTip(_translate("MainWindow", "Activate the non-linear effect: Kerr effect"))
        self.checkBox_kerr.setText(_translate("MainWindow", "Kerr effect"))
        self.label_correction_loop.setText(_translate("MainWindow", "Correction"))
        self.spinBox_kerr_loop.setToolTip(_translate("MainWindow", "Number of corrective loop for the Kerr effect"))
        self.spinBox_kerr_loop.setSuffix(_translate("MainWindow", " loops"))
        self.label_chi3.setToolTip(_translate("MainWindow", "The X(3) Electric susceptibility of the material"))
        self.label_chi3.setText(_translate("MainWindow", "Chi3"))
        self.doubleSpinBox_chi3.setToolTip(_translate("MainWindow", "The X(3) Electric susceptibility of the material"))
        self.doubleSpinBox_chi3.setSuffix(_translate("MainWindow", " * 10^-20 m^2/V^2"))
        self.checkBox_variance.setToolTip(_translate("MainWindow", "Use this control to make sure the intensities converge, but increase drasticly the computation time"))
        self.checkBox_variance.setText(_translate("MainWindow", "Check if intensities converge (slow)"))
        self.estimate_time_display.setToolTip(_translate("MainWindow", "Displayed the estimation time needed to do the propagation"))
        self.estimate_time_display.setStatusTip(_translate("MainWindow", "Show the estimate computation time"))
        self.pushButton_estimate_time.setToolTip(_translate("MainWindow", "When pressed, displayed the estimation time needed to do the propagation"))
        self.pushButton_estimate_time.setText(_translate("MainWindow", "Show estimate time (s)"))
        self.calculateButton_compute.setToolTip(_translate("MainWindow", "Compute beam propagation"))
        self.calculateButton_compute.setText(_translate("MainWindow", "Calculate"))
        self.checkBox_check_power.setToolTip(_translate("MainWindow", "Display the power in each guide as power=sum(I(x))"))
        self.checkBox_check_power.setText(_translate("MainWindow", "Display power"))
        self.pushButton_cancel_compute.setText(_translate("MainWindow", "Cancel changes"))
        self.tabWidget_main.setTabText(self.tabWidget_main.indexOf(self.tabWidget_compute), _translate("MainWindow", "Compute"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
